name: PleromaMC
main: com.kaonashi696.pleromamc.PleromaMC
version: 0.4.1
api-version: 1.13
commands:
   customcmd:
      description: Custom Test Command
      usage: /customcmd
      permission: PleromaMC.test
   
